# Generated by Django 2.2 on 2021-02-13 17:26

from django.db import migrations, models
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktDatenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='INTERESSENSGEMEINSCHAFT SANS-PAPIERS ST.GALLEN ', max_length=355)),
                ('email', models.EmailField(default='info@igsanspapierssg.ch', max_length=300)),
                ('adresse', models.CharField(default='ROSENBERGSTRASSE 73', max_length=355)),
                ('ort', models.CharField(default='9000 St.Gallen', max_length=355)),
                ('telefon', models.CharField(default='+41 76 492 99 69', max_length=355)),
                ('erreichbarkeit', models.CharField(default='Montag & Freitag 14:00 – 17:00 Uhr', max_length=355)),
                ('logo', smartfields.fields.ImageField(blank=True, upload_to='logo/', verbose_name='Logo')),
                ('logo_webp', smartfields.fields.ImageField(blank=True, upload_to='', verbose_name='Logo .webp')),
                ('logo_png', smartfields.fields.ImageField(blank=True, upload_to='', verbose_name='Logo .png')),
            ],
            options={
                'verbose_name': 'Kontaktdaten',
                'verbose_name_plural': 'Kontaktdaten',
                'ordering': ['name'],
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
