# Generated by Django 2.2 on 2021-03-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('info_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontaktdatenmodel',
            name='telefon',
        ),
        migrations.AddField(
            model_name='kontaktdatenmodel',
            name='website',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='kontaktdatenmodel',
            name='adresse',
            field=models.CharField(default='Ringstrasse 12A', max_length=355),
        ),
        migrations.AlterField(
            model_name='kontaktdatenmodel',
            name='email',
            field=models.EmailField(default='info@ambags.ch', max_length=300),
        ),
        migrations.AlterField(
            model_name='kontaktdatenmodel',
            name='name',
            field=models.CharField(default='AMBags', max_length=355),
        ),
        migrations.AlterField(
            model_name='kontaktdatenmodel',
            name='ort',
            field=models.CharField(default='9200 Gossau', max_length=355),
        ),
    ]
