# Generated by Django 2.2 on 2021-03-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0002_auto_20210305_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontaktdatenmodel',
            name='erreichbarkeit',
        ),
    ]
