# Generated by Django 2.2 on 2021-03-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0005_kontaktdatenmodel_ust_idnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontaktdatenmodel',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='kontaktdatenmodel',
            name='logo_png',
        ),
        migrations.RemoveField(
            model_name='kontaktdatenmodel',
            name='logo_webp',
        ),
        migrations.AddField(
            model_name='kontaktdatenmodel',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='kontaktdatenmodel',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Instagram Link'),
        ),
    ]
