# Generated by Django 2.2 on 2021-03-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0006_auto_20210319_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontaktdatenmodel',
            name='unternehmens_sitzort',
            field=models.CharField(default='Hirm', max_length=355),
        ),
    ]
