# Generated by Django 2.2 on 2021-03-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_app', '0007_kontaktdatenmodel_unternehmens_sitzort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontaktdatenmodel',
            name='unternehmens_sitzort',
        ),
        migrations.AddField(
            model_name='kontaktdatenmodel',
            name='unternehmens_sitz',
            field=models.CharField(default='Sitz: Hirm', max_length=355),
        ),
    ]
