# Generated by Django 2.2 on 2021-03-09 15:13

from django.db import migrations, models
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='text')),
                ('bild', smartfields.fields.ImageField(blank=True, null=True, upload_to='photo/%m/')),
                ('bild_png', smartfields.fields.ImageField(blank=True, null=True, upload_to='')),
                ('bild_webp', smartfields.fields.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Beschreibung im Band auf die Homseite',
                'verbose_name_plural': 'Die Beschreibungen im Band auf die Homseite',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
