# Generated by Django 2.2 on 2021-03-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_homeimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeimg',
            name='title',
            field=models.CharField(default='Rado-Montage', max_length=300, verbose_name='Titel'),
        ),
    ]
