# Generated by Django 2.2 on 2021-03-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_homeservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeService',
        ),
    ]
