# Generated by Django 2.2 on 2021-03-16 16:00

from django.db import migrations, models
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_auto_20210316_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': ' Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('url', models.CharField(blank=True, max_length=40, null=True)),
                ('bild', smartfields.fields.ImageField(blank=True, null=True, upload_to='photo/%m/')),
                ('bild_png', smartfields.fields.ImageField(blank=True, null=True, upload_to='')),
                ('bild_webp', smartfields.fields.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Work zum Portfolio',
                'verbose_name_plural': 'Works zum Portfolio',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
