# Generated by Django 2.2 on 2021-03-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_kategorien_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.Kategorien'),
        ),
    ]
