# Generated by Django 2.2 on 2021-03-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0010_remove_projects_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='kategorie',
        ),
        migrations.DeleteModel(
            name='Kategorien',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
