# Generated by Django 2.2 on 2021-03-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0011_auto_20210316_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='title_description',
            field=models.TextField(blank=True, null=True, verbose_name='Untertitel'),
        ),
    ]
