# Generated by Django 2.2 on 2021-03-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_auto_20210318_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'Beschreibung und Bild für die Homeseite', 'verbose_name_plural': 'Beschreibungen und Bilder auf der Homeseite '},
        ),
    ]
