# Generated by Django 2.2 on 2021-03-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_auto_20210323_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'Beschreibung und Bild', 'verbose_name_plural': 'Beschreibungen und Bilder '},
        ),
    ]
