# Generated by Django 2.2 on 2021-03-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impressum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impressummodel',
            options={'verbose_name': 'Impressum oder AGB', 'verbose_name_plural': "Impressum und AGB's "},
        ),
    ]
