# Generated by Django 2.2 on 2021-03-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Abdullah Kroum', max_length=300, verbose_name='Name')),
                ('telefon', models.CharField(blank=True, max_length=300, null=True, verbose_name='Telefon Nr.')),
                ('email', models.CharField(max_length=300, verbose_name='E-Mail')),
                ('adresse', models.CharField(default='Abdullah Kroum', max_length=300, verbose_name='Adresse')),
                ('facebook_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook Link')),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': ' contact infos',
            },
        ),
    ]
