# Generated by Django 2.2 on 2021-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Rado-Montage', max_length=300, verbose_name='Leistung')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung der Leistung')),
            ],
            options={
                'verbose_name': 'Leistung',
                'verbose_name_plural': 'Unsere Leistungen',
            },
        ),
    ]
