# Generated by Django 2.2 on 2021-03-16 14:53

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_auto_20210316_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='bild',
        ),
        migrations.RemoveField(
            model_name='services',
            name='bild_png',
        ),
        migrations.RemoveField(
            model_name='services',
            name='bild_webp',
        ),
        migrations.AddField(
            model_name='services',
            name='icon',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='photo/%m/'),
        ),
    ]
