# Generated by Django 2.2 on 2021-03-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_auto_20210316_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='photo/%m/'),
        ),
    ]
