# Generated by Django 2.2 on 2021-03-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_auto_20210316_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='bild_png',
        ),
        migrations.RemoveField(
            model_name='services',
            name='bild_webp',
        ),
        migrations.AlterField(
            model_name='services',
            name='bild',
            field=models.ImageField(blank=True, upload_to='über_uns_bilder/%m/', verbose_name='Bild ohne Hintergurnd'),
        ),
    ]
