# Generated by Django 2.2 on 2021-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_auto_20210318_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='bild',
            field=models.ImageField(blank=True, upload_to='über_uns_bilder/%m/', verbose_name='Bild ohne Hintergrund'),
        ),
    ]
