# Generated by Django 2.2 on 2021-03-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_auto_20210323_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='bild',
        ),
    ]
