# Generated by Django 2.2 on 2021-03-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekte'},
        ),
    ]
