# Generated by Django 2.2 on 2021-03-18 11:05

from django.db import migrations
import image_cropping.fields
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_auto_20210318_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='cropping',
        ),
        migrations.AddField(
            model_name='projects',
            name='cropping_png',
            field=image_cropping.fields.ImageRatioField('bild_png', '560x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping png'),
        ),
        migrations.AddField(
            model_name='projects',
            name='cropping_webp',
            field=image_cropping.fields.ImageRatioField('bild_webp', '560x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping webp'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='bild_png',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='projects/%m/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='bild_webp',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='projects/%m/'),
        ),
    ]
