# Generated by Django 2.2 on 2021-03-18 12:44

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0009_auto_20210318_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='bild_webp',
        ),
        migrations.AlterField(
            model_name='projects',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('bild', '560x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
