# Generated by Django 2.2 on 2021-03-18 13:34

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0015_auto_20210318_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('bild_webp', '800x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
