# Generated by Django 2.2 on 2021-03-22 19:41

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='text')),
                ('bild', models.ImageField(blank=True, upload_to='über_uns_bilder/%m/', verbose_name='Bild')),
                ('cropping', image_cropping.fields.ImageRatioField('bild', '777x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
            options={
                'verbose_name': 'Beschreibung im Band auf die Homseite',
                'verbose_name_plural': 'Die Beschreibungen im Band auf die Homseite',
            },
        ),
    ]
