# Generated by Django 2.2 on 2021-03-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0002_auto_20210322_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencesText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='text')),
            ],
            options={
                'verbose_name': 'Der erste Text auf Die Homseite',
                'verbose_name_plural': 'Der erste Text auf Die Homseite',
            },
        ),
        migrations.AlterModelOptions(
            name='referencesmodel',
            options={'verbose_name': 'Referenz', 'verbose_name_plural': 'Referenzen'},
        ),
        migrations.AlterField(
            model_name='referencesmodel',
            name='bild',
            field=models.ImageField(blank=True, upload_to='references/%m/', verbose_name='Bild'),
        ),
    ]
