# Generated by Django 2.2 on 2021-03-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0003_auto_20210322_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencestext',
            options={'verbose_name': 'Beschreibung Über unsere Referenzen', 'verbose_name_plural': 'Beschreibung Über unsere Referenzen'},
        ),
    ]
