# Generated by Django 2.2 on 2021-03-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0004_auto_20210323_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencestext',
            options={'verbose_name': 'Beschreibung unserer Referenzen', 'verbose_name_plural': 'Beschreibungen unserer Referenzen'},
        ),
    ]
