# Generated by Django 2.2 on 2021-03-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references_app', '0005_auto_20210323_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencesmodel',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='URL'),
        ),
    ]
