# Generated by Django 2.2 on 2021-03-16 15:38

from django.db import migrations, models
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='text')),
                ('bild', smartfields.fields.ImageField(blank=True, null=True, upload_to='photo/%m/')),
                ('bild_png', smartfields.fields.ImageField(blank=True, null=True, upload_to='')),
                ('bild_webp', smartfields.fields.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Beschreibung im Band auf die Homseite',
                'verbose_name_plural': 'Die Beschreibungen im Band auf die Homseite',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Eine Beschreibung auf die Homeseite',
                'verbose_name_plural': 'Die Beschreibungen auf die Homeseite ',
            },
        ),
        migrations.CreateModel(
            name='AboutImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Rado-Montage', max_length=300, verbose_name='Titel')),
                ('bild', smartfields.fields.ImageField(blank=True, null=True, upload_to='photo/%m/')),
                ('bild_png', smartfields.fields.ImageField(blank=True, null=True, upload_to='')),
                ('bild_webp', smartfields.fields.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Das Foto auf die Homseite',
                'verbose_name_plural': 'Das Foto Auf die Homeseite',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='text')),
            ],
            options={
                'verbose_name': 'Der erste Text auf Die Homseite',
                'verbose_name_plural': 'Der erste Text auf Die Homseite',
            },
        ),
    ]
