# Generated by Django 2.2 on 2021-03-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_aboutband_aboutdescription_aboutimg_abouttext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutContent',
        ),
    ]
