# Generated by Django 2.2 on 2021-03-18 16:32

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0003_delete_aboutcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutband',
            name='bild',
        ),
        migrations.RemoveField(
            model_name='aboutband',
            name='bild_png',
        ),
        migrations.RemoveField(
            model_name='aboutband',
            name='bild_webp',
        ),
        migrations.AddField(
            model_name='abouttext',
            name='bild',
            field=models.ImageField(blank=True, upload_to='projects/%m/', verbose_name='Bild'),
        ),
        migrations.AddField(
            model_name='abouttext',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('bild', '777x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
