# Generated by Django 2.2 on 2021-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0005_auto_20210318_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutband',
            name='bild',
            field=models.ImageField(blank=True, upload_to='über_uns_bilder/%m/', verbose_name='Bild'),
        ),
    ]
