# Generated by Django 2.2 on 2021-03-18 21:15

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0006_auto_20210318_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('position', models.CharField(max_length=300, verbose_name='Aufgabe')),
                ('bild', models.ImageField(blank=True, upload_to='über_uns_bilder/%m/', verbose_name='Fhoto')),
                ('cropping', image_cropping.fields.ImageRatioField('Fhoto', '400x465', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Unser Team',
            },
        ),
    ]
