# Generated by Django 2.2 on 2021-03-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0008_auto_20210318_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='team/%m/', verbose_name='Photo'),
        ),
    ]
