# Generated by Django 2.2 on 2021-03-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0009_auto_20210318_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutBand',
        ),
    ]
