# Generated by Django 2.2 on 2021-03-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0010_delete_aboutband'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutText',
        ),
        migrations.AlterModelOptions(
            name='aboutdescription',
            options={'verbose_name': 'Eigenschaft', 'verbose_name_plural': 'Eigenschaften '},
        ),
        migrations.AlterModelOptions(
            name='aboutimg',
            options={'verbose_name': 'Hauptfoto', 'verbose_name_plural': 'Hauptfotos'},
        ),
        migrations.AddField(
            model_name='aboutimg',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='aboutimg',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Titel'),
        ),
    ]
