# Generated by Django 2.2 on 2021-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0011_auto_20210323_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimg',
            options={'verbose_name': 'Überschrift und Hauptfoto', 'verbose_name_plural': 'Überschriften und Hauptfotos'},
        ),
        migrations.AlterModelOptions(
            name='teammodel',
            options={'verbose_name': 'Teammitglied', 'verbose_name_plural': 'Teammitglieder'},
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to='team/%m/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='position',
            field=models.CharField(max_length=300, verbose_name='Aufgabenbereich'),
        ),
    ]
